import { Member } from './types'

export const initialMembers: Member[] = [
  {
    id: '1',
    name: 'Hamza Khan',
    initials: 'HK',
    phone: '0300-5551234',
    gender: 'Male',
    plan: 'Treadmill Pro',
    monthlyFee: 7500,
    joinDate: 'Jan 12, 2024',
    paymentDate: 'Mar 01, 2024',
    status: 'Active',
    color: 'lime',
  },
  {
    id: '2',
    name: 'Ayesha Malik',
    initials: 'AM',
    phone: '0321-9876543',
    gender: 'Female',
    plan: 'Treadmill Pro',
    monthlyFee: 7500,
    joinDate: 'Feb 08, 2024',
    paymentDate: 'Feb 28, 2024',
    status: 'Due Soon',
    color: 'violet',
  },
  {
    id: '3',
    name: 'Bilawal Ahmed',
    initials: 'BA',
    phone: '0333-4445566',
    gender: 'Male',
    plan: 'Standard Gym',
    monthlyFee: 5000,
    joinDate: 'Dec 19, 2023',
    paymentDate: 'Feb 04, 2024',
    status: 'Overdue',
    color: 'orange',
  },
  {
    id: '4',
    name: 'Zainab Chaudhry',
    initials: 'ZC',
    phone: '',
    gender: 'Female',
    plan: 'Standard Gym',
    monthlyFee: 5000,
    joinDate: 'Mar 03, 2024',
    paymentDate: 'Mar 03, 2024',
    status: 'Active',
    color: 'pink',
  },
  {
    id: '5',
    name: 'Usman Ali',
    initials: 'UA',
    phone: '0345-1122334',
    gender: 'Male',
    plan: 'Treadmill Pro',
    monthlyFee: 7500,
    joinDate: 'Jan 26, 2024',
    paymentDate: 'Feb 25, 2024',
    status: 'Due Soon',
    color: 'blue',
  },
  {
    id: '6',
    name: 'Fatima Raza',
    initials: 'FR',
    phone: '0302-8899000',
    gender: 'Female',
    plan: 'Standard Gym',
    monthlyFee: 5000,
    joinDate: 'Nov 14, 2023',
    paymentDate: 'Jan 30, 2024',
    status: 'Overdue',
    color: 'cyan',
  },
]

export const avatarColors: Record<string, string> = {
  lime: 'bg-lime-400/20 text-lime-400 border border-lime-500/30',
  blue: 'bg-sky-400/20 text-sky-400 border border-sky-500/30',
  violet: 'bg-violet-400/20 text-violet-400 border border-violet-500/30',
  orange: 'bg-orange-400/20 text-orange-400 border border-orange-500/30',
  pink: 'bg-pink-400/20 text-pink-400 border border-pink-500/30',
  cyan: 'bg-cyan-400/20 text-cyan-400 border border-cyan-500/30',
}

export function formatPKR(amount: number): string {
  return new Intl.NumberFormat('en-PK', {
    style: 'currency',
    currency: 'PKR',
    maximumFractionDigits: 0,
  }).format(amount).replace('PKR', 'Rs.')
}
